### ISSUE TITLE
OSX /sbin/poweroff/ No such file or directory

### ISSUE THREAD

**Issue by Aratramba** [typicode/stop-server#3]
I haven't tested this, but just wanted to let you know there is no `/sbin/poweroff/` on my version of osx. There is a `/sbin/shutdown/` however, so this might be what you need here. I'm on OS X Yosemite (10.10.4)

**Comment by typicode** [comment]
Thank you for letting me know!
It should be good now.

**Comment by Aratramba** [comment]
seems to be working fine now.
