### ISSUE TITLE
/etc/sudoers: syntax error near line 1 <<<

### ISSUE THREAD

**Issue by Aratramba** [typicode/stop-server#4]
trying to run `sudo visudo` with `your-username ALL=NOPASSWD: /sbin/poweroff` gave me this error:

``` bash
>>> /etc/sudoers: syntax error near line 1 <<<
```

![screen shot 2015-09-28 at 09 05 35](https://cloud.githubusercontent.com/assets/580312/10129598/1dbe55ee-65c0-11e5-8da6-8560f1234cd9.png)

**Comment by typicode** [comment]
I've updated the README for OS X, can you retry?
On Linux, I have `typicode ALL=NOPASSWD: /sbin/poweroff`. I'll test again.

**Comment by Aratramba** [comment]
testing right now. First thing I see when running `stop-server start` is the old command in my terminal.

``` bash
To complete installation, you need to allow the 'poweroff' command to be run without admin password.
  Please run `sudo visudo` and add `your-username ALL=NOPASSWD: /sbin/poweroff`
```

**Comment by Aratramba** [comment]
not working:
`-bash: fg: %users: no such job`

also the thing with `# On OS X, run 'sudo visudo' and uncomment/add` is that the opened file is empty - so there's nothing to uncomment.

![screen shot 2015-09-28 at 14 40 04](https://cloud.githubusercontent.com/assets/580312/10135503/d4b42a3e-65ee-11e5-9139-9630c28b4bf7.png)

**Comment by typicode** [comment]
Strange :/ when running `sudo visudo`, I have something like this in the terminal (OS X 10.10.3)

```
# sudoers file.
#
# This file MUST be edited with the 'visudo' command as root.
# Failure to use 'visudo' may result in syntax or file permission errors
# that prevent sudo from running.
#
# See the sudoers man page for the details on how to write a sudoers file.
#

# Host alias specification

# User alias specification

# Cmnd alias specification

# ...

# Uncomment to allow people in group wheel to run all commands
# %wheel        ALL=(ALL) ALL

# Same thing without a password
# %wheel        ALL=(ALL) NOPASSWD: ALL

# Samples
# %users  ALL=/sbin/mount /cdrom,/sbin/umount /cdrom
%users  localhost=/sbin/shutdown -h now
```

**Comment by Aratramba** [comment]
I got it running with `EDITOR=nano visudo`. This opens the sudoers file in Nano instead of in Sublime Text.

**Comment by Aratramba** [comment]
…after shutdown… all works as expected now.

**Comment by Aratramba** [comment]
I was om 0.1.4 before, 0.2.0 seems to be working fine as well. I think this one can be closed. Maybe update the readme with the EDITOR=nano thing.

**Comment by typicode** [comment]
Thanks for the update :) closing it.

AFAIK it's vi or nano by default, so it shouldn't occur too often. If there's more issue like that I'll update the README.
