### ISSUE TITLE
sleep-server

### ISSUE THREAD

**Issue by Aratramba** [typicode/stop-server#8]
how about an option to let the computer go to sleep instead of shutting it down completely. Might be a nice feature for laptops.

**Comment by typicode** [comment]
I agree. For the short story, that's part of the reason I named it stop-server instead of shutdown ^_^
@hemanth want to create a sleep package?

**Comment by hemanth** [comment]
Sure! Give me sometime.

**Comment by hemanth** [comment]
@typicode There you go [sleep-mode](https://github.com/hemanth/sleep-mode) :wink:

**Comment by typicode** [comment]
Awesome! Thank you :+1:

**Comment by typicode** [comment]
Published (`v0.3.0`) :)

**Comment by hemanth** [comment]
:+1:
